stages:
    - test

test:
    stage: test
    image: python:3.8-alpine
    script:
        - echo "Testing"
        - pip3 install --upgrade pip
        - pip3 install -r requirements.txt
        - pip3 install coverage
        - coverage run --source=app --branch -m discover test
        - coverage report -m
        - coverage html -d coverage_reports
    artifacts:
        paths:
            - coverage_reports/