stages:
    - test

test:
    stage: test
    image: python:3.8-alpine
    script:
        - echo "Testing"
        - pip3 install --upgrade pip
        - pip3 install -r requirements.txt
        - python3 -m unittest test/calculator_blackbox_unittest.py
        - python3 -m unittest test/calculator_solarapi_unittest.py
        - python3 -m unittest test/state_holidat_unittest.py